/** Declaration file generated by dts-gen */

declare module "ldap-escape" {
	function dn(strings: TemplateStringsArray, ...options: any[]): string;
	function filter(strings: TemplateStringsArray, ...options: any[]): string;
}
